name: Emotion Tracker
version: 0.0.1
summary: Super Cool App
description: Super Cool App that does everything!

confinement: strict
base: core22
grade: stable

slots:
  dbus-emotion-tracker: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: in.rohanbatra.emotion-tracker # adjust accordingly to your app name and
    
apps:
  emotion-tracker:
    command: emotion-tracker
    extensions: [gnome] # gnome includes the libraries required by flutter
    plugs:
    - network
    slots:
      - dbus-emotion-tracker
parts:
  emotion-tracker:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application