name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger deployment on PR to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Flutter (specify an exact version compatible with emotion_tracker)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2

                 
      # Install dependencies
      - name: Switching to beta 
        run: |
          flutter channel beta
      
      - name: Reflecting beta changes
        run: |
          flutter create .

      # Install dependencies
      - name: Enabling Web 
        run: |
          flutter config --enable-web
         
      # Install dependencies
      - name: Install dependencies
        run: |
          flutter pub get

      # Build the Flutter web app
      - name: Build Flutter web app
        run: |
          flutter build web --release

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          # Required: Build directory to deploy
          build_dir: build/web
      
          # GitHub repository where assets will be deployed (default is the current repository)
          repo: ${{ github.repository }}
      
          # Git branch where assets will be deployed (default is gh-pages)
          target_branch: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Provide token via environment variable
