name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Build Flutter web app
        run: |
          flutter build web --release

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          build_dir: build/web  # Build directory to deploy
          repo: ${{ github.repository }}  # GitHub repository to deploy to
          target_branch: gh-pages  # Git branch to deploy to
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Provide token via environment variable
